// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://anroupufmgubgskbsiqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFucm91cHVmbWd1Ymdza2JzaXFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMzIxNjMsImV4cCI6MjA2NTcwODE2M30.4qxMVQhbus16PhIqvflous7uI9zeLnGDo4KQGxs7sHo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);